// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: streams.proto

package streamspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderEventPayload is the payload for Redis stream "orderEvent" (single "payload" field).
type OrderEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Bs            string                 `protobuf:"bytes,2,opt,name=bs,proto3" json:"bs,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Pending       float64                `protobuf:"fixed64,6,opt,name=pending,proto3" json:"pending,omitempty"`
	Filled        float64                `protobuf:"fixed64,7,opt,name=filled,proto3" json:"filled,omitempty"`
	AvgPrice      float64                `protobuf:"fixed64,8,opt,name=avgPrice,proto3" json:"avgPrice,omitempty"`
	OrderID       string                 `protobuf:"bytes,9,opt,name=orderID,proto3" json:"orderID,omitempty"`
	MessageError  string                 `protobuf:"bytes,10,opt,name=messageError,proto3" json:"messageError,omitempty"`
	Remark        string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	BasketID      string                 `protobuf:"bytes,12,opt,name=basketID,proto3" json:"basketID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEventPayload) Reset() {
	*x = OrderEventPayload{}
	mi := &file_streams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEventPayload) ProtoMessage() {}

func (x *OrderEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEventPayload.ProtoReflect.Descriptor instead.
func (*OrderEventPayload) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{0}
}

func (x *OrderEventPayload) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *OrderEventPayload) GetBs() string {
	if x != nil {
		return x.Bs
	}
	return ""
}

func (x *OrderEventPayload) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderEventPayload) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderEventPayload) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderEventPayload) GetPending() float64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *OrderEventPayload) GetFilled() float64 {
	if x != nil {
		return x.Filled
	}
	return 0
}

func (x *OrderEventPayload) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *OrderEventPayload) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *OrderEventPayload) GetMessageError() string {
	if x != nil {
		return x.MessageError
	}
	return ""
}

func (x *OrderEventPayload) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderEventPayload) GetBasketID() string {
	if x != nil {
		return x.BasketID
	}
	return ""
}

// TradeEventPayload is the payload for Redis stream "tradeEvent".
type TradeEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Volume        string                 `protobuf:"bytes,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeEventPayload) Reset() {
	*x = TradeEventPayload{}
	mi := &file_streams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeEventPayload) ProtoMessage() {}

func (x *TradeEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeEventPayload.ProtoReflect.Descriptor instead.
func (*TradeEventPayload) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{1}
}

func (x *TradeEventPayload) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *TradeEventPayload) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *TradeEventPayload) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *TradeEventPayload) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

// --- orderbook.update ---
type ActiveRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinPrice      float64                `protobuf:"fixed64,1,opt,name=minPrice,proto3" json:"minPrice,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,2,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveRange) Reset() {
	*x = ActiveRange{}
	mi := &file_streams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveRange) ProtoMessage() {}

func (x *ActiveRange) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveRange.ProtoReflect.Descriptor instead.
func (*ActiveRange) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{2}
}

func (x *ActiveRange) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ActiveRange) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type PriceLevel struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Price              float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	MarketBidQty       float64                `protobuf:"fixed64,2,opt,name=marketBidQty,proto3" json:"marketBidQty,omitempty"`
	MarketAskQty       float64                `protobuf:"fixed64,3,opt,name=marketAskQty,proto3" json:"marketAskQty,omitempty"`
	UserPendingBuyQty  float64                `protobuf:"fixed64,4,opt,name=userPendingBuyQty,proto3" json:"userPendingBuyQty,omitempty"`
	UserPendingSellQty float64                `protobuf:"fixed64,5,opt,name=userPendingSellQty,proto3" json:"userPendingSellQty,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_streams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{3}
}

func (x *PriceLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceLevel) GetMarketBidQty() float64 {
	if x != nil {
		return x.MarketBidQty
	}
	return 0
}

func (x *PriceLevel) GetMarketAskQty() float64 {
	if x != nil {
		return x.MarketAskQty
	}
	return 0
}

func (x *PriceLevel) GetUserPendingBuyQty() float64 {
	if x != nil {
		return x.UserPendingBuyQty
	}
	return 0
}

func (x *PriceLevel) GetUserPendingSellQty() float64 {
	if x != nil {
		return x.UserPendingSellQty
	}
	return 0
}

type OrderbookUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Floor         float64                `protobuf:"fixed64,2,opt,name=floor,proto3" json:"floor,omitempty"`
	Ceiling       float64                `protobuf:"fixed64,3,opt,name=ceiling,proto3" json:"ceiling,omitempty"`
	PriceStep     float64                `protobuf:"fixed64,4,opt,name=priceStep,proto3" json:"priceStep,omitempty"`
	ActiveRange   *ActiveRange           `protobuf:"bytes,5,opt,name=activeRange,proto3" json:"activeRange,omitempty"`
	Levels        []*PriceLevel          `protobuf:"bytes,6,rep,name=levels,proto3" json:"levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderbookUpdate) Reset() {
	*x = OrderbookUpdate{}
	mi := &file_streams_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderbookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderbookUpdate) ProtoMessage() {}

func (x *OrderbookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderbookUpdate.ProtoReflect.Descriptor instead.
func (*OrderbookUpdate) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{4}
}

func (x *OrderbookUpdate) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *OrderbookUpdate) GetFloor() float64 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *OrderbookUpdate) GetCeiling() float64 {
	if x != nil {
		return x.Ceiling
	}
	return 0
}

func (x *OrderbookUpdate) GetPriceStep() float64 {
	if x != nil {
		return x.PriceStep
	}
	return 0
}

func (x *OrderbookUpdate) GetActiveRange() *ActiveRange {
	if x != nil {
		return x.ActiveRange
	}
	return nil
}

func (x *OrderbookUpdate) GetLevels() []*PriceLevel {
	if x != nil {
		return x.Levels
	}
	return nil
}

// --- portfolio.PL ---
type PortfolioPLResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilledBuy     float64                `protobuf:"fixed64,1,opt,name=filledBuy,proto3" json:"filledBuy,omitempty"`
	FilledSell    float64                `protobuf:"fixed64,2,opt,name=filledSell,proto3" json:"filledSell,omitempty"`
	NetFilled     float64                `protobuf:"fixed64,3,opt,name=netFilled,proto3" json:"netFilled,omitempty"`
	PendingBuy    float64                `protobuf:"fixed64,4,opt,name=pendingBuy,proto3" json:"pendingBuy,omitempty"`
	PendingSell   float64                `protobuf:"fixed64,5,opt,name=pendingSell,proto3" json:"pendingSell,omitempty"`
	NetPending    float64                `protobuf:"fixed64,6,opt,name=netPending,proto3" json:"netPending,omitempty"`
	Fee           float64                `protobuf:"fixed64,7,opt,name=fee,proto3" json:"fee,omitempty"`
	Pl            float64                `protobuf:"fixed64,8,opt,name=pl,proto3" json:"pl,omitempty"`
	CapitalUsed   float64                `protobuf:"fixed64,9,opt,name=capitalUsed,proto3" json:"capitalUsed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioPLResult) Reset() {
	*x = PortfolioPLResult{}
	mi := &file_streams_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioPLResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioPLResult) ProtoMessage() {}

func (x *PortfolioPLResult) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioPLResult.ProtoReflect.Descriptor instead.
func (*PortfolioPLResult) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{5}
}

func (x *PortfolioPLResult) GetFilledBuy() float64 {
	if x != nil {
		return x.FilledBuy
	}
	return 0
}

func (x *PortfolioPLResult) GetFilledSell() float64 {
	if x != nil {
		return x.FilledSell
	}
	return 0
}

func (x *PortfolioPLResult) GetNetFilled() float64 {
	if x != nil {
		return x.NetFilled
	}
	return 0
}

func (x *PortfolioPLResult) GetPendingBuy() float64 {
	if x != nil {
		return x.PendingBuy
	}
	return 0
}

func (x *PortfolioPLResult) GetPendingSell() float64 {
	if x != nil {
		return x.PendingSell
	}
	return 0
}

func (x *PortfolioPLResult) GetNetPending() float64 {
	if x != nil {
		return x.NetPending
	}
	return 0
}

func (x *PortfolioPLResult) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *PortfolioPLResult) GetPl() float64 {
	if x != nil {
		return x.Pl
	}
	return 0
}

func (x *PortfolioPLResult) GetCapitalUsed() float64 {
	if x != nil {
		return x.CapitalUsed
	}
	return 0
}

type PortfolioPLPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *PortfolioPLResult     `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	Etf           *PortfolioPLResult     `protobuf:"bytes,2,opt,name=etf,proto3" json:"etf,omitempty"`
	Future        *PortfolioPLResult     `protobuf:"bytes,3,opt,name=future,proto3" json:"future,omitempty"`
	Total         *PortfolioPLResult     `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	LastUpdate    int64                  `protobuf:"varint,5,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioPLPayload) Reset() {
	*x = PortfolioPLPayload{}
	mi := &file_streams_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioPLPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioPLPayload) ProtoMessage() {}

func (x *PortfolioPLPayload) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioPLPayload.ProtoReflect.Descriptor instead.
func (*PortfolioPLPayload) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{6}
}

func (x *PortfolioPLPayload) GetStock() *PortfolioPLResult {
	if x != nil {
		return x.Stock
	}
	return nil
}

func (x *PortfolioPLPayload) GetEtf() *PortfolioPLResult {
	if x != nil {
		return x.Etf
	}
	return nil
}

func (x *PortfolioPLPayload) GetFuture() *PortfolioPLResult {
	if x != nil {
		return x.Future
	}
	return nil
}

func (x *PortfolioPLPayload) GetTotal() *PortfolioPLResult {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *PortfolioPLPayload) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

// --- legs.PL ---
type LegsPLData struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FilledBuyQty         float64                `protobuf:"fixed64,1,opt,name=filledBuyQty,proto3" json:"filledBuyQty,omitempty"`
	FilledBuyValue       float64                `protobuf:"fixed64,2,opt,name=filledBuyValue,proto3" json:"filledBuyValue,omitempty"`
	FilledSellQty        float64                `protobuf:"fixed64,3,opt,name=filledSellQty,proto3" json:"filledSellQty,omitempty"`
	FilledSellValue      float64                `protobuf:"fixed64,4,opt,name=filledSellValue,proto3" json:"filledSellValue,omitempty"`
	PendingBuyQty        float64                `protobuf:"fixed64,5,opt,name=pendingBuyQty,proto3" json:"pendingBuyQty,omitempty"`
	PendingBuyValue      float64                `protobuf:"fixed64,6,opt,name=pendingBuyValue,proto3" json:"pendingBuyValue,omitempty"`
	PendingSellQty       float64                `protobuf:"fixed64,7,opt,name=pendingSellQty,proto3" json:"pendingSellQty,omitempty"`
	PendingSellValue     float64                `protobuf:"fixed64,8,opt,name=pendingSellValue,proto3" json:"pendingSellValue,omitempty"`
	Fee                  float64                `protobuf:"fixed64,9,opt,name=fee,proto3" json:"fee,omitempty"`
	UnitCost             float64                `protobuf:"fixed64,10,opt,name=unitCost,proto3" json:"unitCost,omitempty"`
	UnrealizedPL         float64                `protobuf:"fixed64,11,opt,name=unrealizedPL,proto3" json:"unrealizedPL,omitempty"`
	RealizedPL           float64                `protobuf:"fixed64,12,opt,name=realizedPL,proto3" json:"realizedPL,omitempty"`
	TotalPL              float64                `protobuf:"fixed64,13,opt,name=totalPL,proto3" json:"totalPL,omitempty"`
	TradingPL            float64                `protobuf:"fixed64,14,opt,name=tradingPL,proto3" json:"tradingPL,omitempty"`
	BeginningQty         float64                `protobuf:"fixed64,15,opt,name=beginningQty,proto3" json:"beginningQty,omitempty"`
	TradableQty          float64                `protobuf:"fixed64,16,opt,name=tradableQty,proto3" json:"tradableQty,omitempty"`
	BeginningTradableQty float64                `protobuf:"fixed64,17,opt,name=beginningTradableQty,proto3" json:"beginningTradableQty,omitempty"`
	DueBuyQty            float64                `protobuf:"fixed64,18,opt,name=dueBuyQty,proto3" json:"dueBuyQty,omitempty"`
	T1CreateQty          float64                `protobuf:"fixed64,19,opt,name=t1CreateQty,proto3" json:"t1CreateQty,omitempty"`
	UnsettledStockQty    float64                `protobuf:"fixed64,20,opt,name=unsettledStockQty,proto3" json:"unsettledStockQty,omitempty"`
	T1Qty                float64                `protobuf:"fixed64,21,opt,name=t1Qty,proto3" json:"t1Qty,omitempty"`
	CreateQty            float64                `protobuf:"fixed64,22,opt,name=createQty,proto3" json:"createQty,omitempty"`
	CreateValue          float64                `protobuf:"fixed64,23,opt,name=createValue,proto3" json:"createValue,omitempty"`
	RedeemQty            float64                `protobuf:"fixed64,24,opt,name=redeemQty,proto3" json:"redeemQty,omitempty"`
	RedeemValue          float64                `protobuf:"fixed64,25,opt,name=redeemValue,proto3" json:"redeemValue,omitempty"`
	FailedCreateQty      float64                `protobuf:"fixed64,26,opt,name=failedCreateQty,proto3" json:"failedCreateQty,omitempty"`
	FailedCreateValue    float64                `protobuf:"fixed64,27,opt,name=failedCreateValue,proto3" json:"failedCreateValue,omitempty"`
	FailedRedeemQty      float64                `protobuf:"fixed64,28,opt,name=failedRedeemQty,proto3" json:"failedRedeemQty,omitempty"`
	FailedRedeemValue    float64                `protobuf:"fixed64,29,opt,name=failedRedeemValue,proto3" json:"failedRedeemValue,omitempty"`
	DividendQty          float64                `protobuf:"fixed64,30,opt,name=dividendQty,proto3" json:"dividendQty,omitempty"`
	Cash                 float64                `protobuf:"fixed64,31,opt,name=cash,proto3" json:"cash,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LegsPLData) Reset() {
	*x = LegsPLData{}
	mi := &file_streams_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegsPLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegsPLData) ProtoMessage() {}

func (x *LegsPLData) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegsPLData.ProtoReflect.Descriptor instead.
func (*LegsPLData) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{7}
}

func (x *LegsPLData) GetFilledBuyQty() float64 {
	if x != nil {
		return x.FilledBuyQty
	}
	return 0
}

func (x *LegsPLData) GetFilledBuyValue() float64 {
	if x != nil {
		return x.FilledBuyValue
	}
	return 0
}

func (x *LegsPLData) GetFilledSellQty() float64 {
	if x != nil {
		return x.FilledSellQty
	}
	return 0
}

func (x *LegsPLData) GetFilledSellValue() float64 {
	if x != nil {
		return x.FilledSellValue
	}
	return 0
}

func (x *LegsPLData) GetPendingBuyQty() float64 {
	if x != nil {
		return x.PendingBuyQty
	}
	return 0
}

func (x *LegsPLData) GetPendingBuyValue() float64 {
	if x != nil {
		return x.PendingBuyValue
	}
	return 0
}

func (x *LegsPLData) GetPendingSellQty() float64 {
	if x != nil {
		return x.PendingSellQty
	}
	return 0
}

func (x *LegsPLData) GetPendingSellValue() float64 {
	if x != nil {
		return x.PendingSellValue
	}
	return 0
}

func (x *LegsPLData) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *LegsPLData) GetUnitCost() float64 {
	if x != nil {
		return x.UnitCost
	}
	return 0
}

func (x *LegsPLData) GetUnrealizedPL() float64 {
	if x != nil {
		return x.UnrealizedPL
	}
	return 0
}

func (x *LegsPLData) GetRealizedPL() float64 {
	if x != nil {
		return x.RealizedPL
	}
	return 0
}

func (x *LegsPLData) GetTotalPL() float64 {
	if x != nil {
		return x.TotalPL
	}
	return 0
}

func (x *LegsPLData) GetTradingPL() float64 {
	if x != nil {
		return x.TradingPL
	}
	return 0
}

func (x *LegsPLData) GetBeginningQty() float64 {
	if x != nil {
		return x.BeginningQty
	}
	return 0
}

func (x *LegsPLData) GetTradableQty() float64 {
	if x != nil {
		return x.TradableQty
	}
	return 0
}

func (x *LegsPLData) GetBeginningTradableQty() float64 {
	if x != nil {
		return x.BeginningTradableQty
	}
	return 0
}

func (x *LegsPLData) GetDueBuyQty() float64 {
	if x != nil {
		return x.DueBuyQty
	}
	return 0
}

func (x *LegsPLData) GetT1CreateQty() float64 {
	if x != nil {
		return x.T1CreateQty
	}
	return 0
}

func (x *LegsPLData) GetUnsettledStockQty() float64 {
	if x != nil {
		return x.UnsettledStockQty
	}
	return 0
}

func (x *LegsPLData) GetT1Qty() float64 {
	if x != nil {
		return x.T1Qty
	}
	return 0
}

func (x *LegsPLData) GetCreateQty() float64 {
	if x != nil {
		return x.CreateQty
	}
	return 0
}

func (x *LegsPLData) GetCreateValue() float64 {
	if x != nil {
		return x.CreateValue
	}
	return 0
}

func (x *LegsPLData) GetRedeemQty() float64 {
	if x != nil {
		return x.RedeemQty
	}
	return 0
}

func (x *LegsPLData) GetRedeemValue() float64 {
	if x != nil {
		return x.RedeemValue
	}
	return 0
}

func (x *LegsPLData) GetFailedCreateQty() float64 {
	if x != nil {
		return x.FailedCreateQty
	}
	return 0
}

func (x *LegsPLData) GetFailedCreateValue() float64 {
	if x != nil {
		return x.FailedCreateValue
	}
	return 0
}

func (x *LegsPLData) GetFailedRedeemQty() float64 {
	if x != nil {
		return x.FailedRedeemQty
	}
	return 0
}

func (x *LegsPLData) GetFailedRedeemValue() float64 {
	if x != nil {
		return x.FailedRedeemValue
	}
	return 0
}

func (x *LegsPLData) GetDividendQty() float64 {
	if x != nil {
		return x.DividendQty
	}
	return 0
}

func (x *LegsPLData) GetCash() float64 {
	if x != nil {
		return x.Cash
	}
	return 0
}

type LegsPLPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	AssetType     string                 `protobuf:"bytes,2,opt,name=assetType,proto3" json:"assetType,omitempty"`
	Data          *LegsPLData            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	AsOf          int64                  `protobuf:"varint,4,opt,name=asOf,proto3" json:"asOf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LegsPLPayload) Reset() {
	*x = LegsPLPayload{}
	mi := &file_streams_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegsPLPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegsPLPayload) ProtoMessage() {}

func (x *LegsPLPayload) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegsPLPayload.ProtoReflect.Descriptor instead.
func (*LegsPLPayload) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{8}
}

func (x *LegsPLPayload) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *LegsPLPayload) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *LegsPLPayload) GetData() *LegsPLData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LegsPLPayload) GetAsOf() int64 {
	if x != nil {
		return x.AsOf
	}
	return 0
}

// --- basisArb.basket.update / basisArb.basket ---
type BasketState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Side            string                 `protobuf:"bytes,1,opt,name=side,proto3" json:"side,omitempty"`
	BasketTarget    float64                `protobuf:"fixed64,2,opt,name=basketTarget,proto3" json:"basketTarget,omitempty"`
	BasketExecuted  float64                `protobuf:"fixed64,3,opt,name=basketExecuted,proto3" json:"basketExecuted,omitempty"`
	BasketInitial   float64                `protobuf:"fixed64,4,opt,name=basketInitial,proto3" json:"basketInitial,omitempty"`
	FuturesTarget   float64                `protobuf:"fixed64,5,opt,name=futuresTarget,proto3" json:"futuresTarget,omitempty"`
	FuturesExecuted float64                `protobuf:"fixed64,6,opt,name=futuresExecuted,proto3" json:"futuresExecuted,omitempty"`
	FuturesInitial  float64                `protobuf:"fixed64,7,opt,name=futuresInitial,proto3" json:"futuresInitial,omitempty"`
	BasisTarget     float64                `protobuf:"fixed64,8,opt,name=basisTarget,proto3" json:"basisTarget,omitempty"`
	BasisNow        float64                `protobuf:"fixed64,9,opt,name=basisNow,proto3" json:"basisNow,omitempty"`
	BasisInitial    float64                `protobuf:"fixed64,10,opt,name=basisInitial,proto3" json:"basisInitial,omitempty"`
	Status          string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	BasketName      string                 `protobuf:"bytes,12,opt,name=basketName,proto3" json:"basketName,omitempty"`
	BasketID        string                 `protobuf:"bytes,13,opt,name=basketID,proto3" json:"basketID,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Zscore          float64                `protobuf:"fixed64,15,opt,name=zscore,proto3" json:"zscore,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BasketState) Reset() {
	*x = BasketState{}
	mi := &file_streams_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketState) ProtoMessage() {}

func (x *BasketState) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketState.ProtoReflect.Descriptor instead.
func (*BasketState) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{9}
}

func (x *BasketState) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *BasketState) GetBasketTarget() float64 {
	if x != nil {
		return x.BasketTarget
	}
	return 0
}

func (x *BasketState) GetBasketExecuted() float64 {
	if x != nil {
		return x.BasketExecuted
	}
	return 0
}

func (x *BasketState) GetBasketInitial() float64 {
	if x != nil {
		return x.BasketInitial
	}
	return 0
}

func (x *BasketState) GetFuturesTarget() float64 {
	if x != nil {
		return x.FuturesTarget
	}
	return 0
}

func (x *BasketState) GetFuturesExecuted() float64 {
	if x != nil {
		return x.FuturesExecuted
	}
	return 0
}

func (x *BasketState) GetFuturesInitial() float64 {
	if x != nil {
		return x.FuturesInitial
	}
	return 0
}

func (x *BasketState) GetBasisTarget() float64 {
	if x != nil {
		return x.BasisTarget
	}
	return 0
}

func (x *BasketState) GetBasisNow() float64 {
	if x != nil {
		return x.BasisNow
	}
	return 0
}

func (x *BasketState) GetBasisInitial() float64 {
	if x != nil {
		return x.BasisInitial
	}
	return 0
}

func (x *BasketState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BasketState) GetBasketName() string {
	if x != nil {
		return x.BasketName
	}
	return ""
}

func (x *BasketState) GetBasketID() string {
	if x != nil {
		return x.BasketID
	}
	return ""
}

func (x *BasketState) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BasketState) GetZscore() float64 {
	if x != nil {
		return x.Zscore
	}
	return 0
}

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bs            string                 `protobuf:"bytes,1,opt,name=bs,proto3" json:"bs,omitempty"`
	OrderID       string                 `protobuf:"bytes,2,opt,name=orderID,proto3" json:"orderID,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Ticker        string                 `protobuf:"bytes,6,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_streams_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{10}
}

func (x *OrderInfo) GetBs() string {
	if x != nil {
		return x.Bs
	}
	return ""
}

func (x *OrderInfo) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *OrderInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderInfo) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderInfo) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type BasketUpdatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasketID      string                 `protobuf:"bytes,1,opt,name=basketID,proto3" json:"basketID,omitempty"`
	Basket        *BasketState           `protobuf:"bytes,2,opt,name=basket,proto3" json:"basket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasketUpdatePayload) Reset() {
	*x = BasketUpdatePayload{}
	mi := &file_streams_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketUpdatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketUpdatePayload) ProtoMessage() {}

func (x *BasketUpdatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketUpdatePayload.ProtoReflect.Descriptor instead.
func (*BasketUpdatePayload) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{11}
}

func (x *BasketUpdatePayload) GetBasketID() string {
	if x != nil {
		return x.BasketID
	}
	return ""
}

func (x *BasketUpdatePayload) GetBasket() *BasketState {
	if x != nil {
		return x.Basket
	}
	return nil
}

type BasketDataPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasketID      string                 `protobuf:"bytes,1,opt,name=basketID,proto3" json:"basketID,omitempty"`
	Basket        *BasketState           `protobuf:"bytes,2,opt,name=basket,proto3" json:"basket,omitempty"`
	Orders        []*OrderInfo           `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasketDataPayload) Reset() {
	*x = BasketDataPayload{}
	mi := &file_streams_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketDataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketDataPayload) ProtoMessage() {}

func (x *BasketDataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketDataPayload.ProtoReflect.Descriptor instead.
func (*BasketDataPayload) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{12}
}

func (x *BasketDataPayload) GetBasketID() string {
	if x != nil {
		return x.BasketID
	}
	return ""
}

func (x *BasketDataPayload) GetBasket() *BasketState {
	if x != nil {
		return x.Basket
	}
	return nil
}

func (x *BasketDataPayload) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

// --- sendOrderEvent ---
type SendOrderCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "Send", "Modify", "Cancel", "Offset"
	BasketID      string                 `protobuf:"bytes,2,opt,name=basketID,proto3" json:"basketID,omitempty"`
	SlowMode      bool                   `protobuf:"varint,3,opt,name=slowMode,proto3" json:"slowMode,omitempty"`
	Orders        []*SendOrderOrder      `protobuf:"bytes,4,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrderCommand) Reset() {
	*x = SendOrderCommand{}
	mi := &file_streams_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderCommand) ProtoMessage() {}

func (x *SendOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderCommand.ProtoReflect.Descriptor instead.
func (*SendOrderCommand) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{13}
}

func (x *SendOrderCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SendOrderCommand) GetBasketID() string {
	if x != nil {
		return x.BasketID
	}
	return ""
}

func (x *SendOrderCommand) GetSlowMode() bool {
	if x != nil {
		return x.SlowMode
	}
	return false
}

func (x *SendOrderCommand) GetOrders() []*SendOrderOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

type SendOrderOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Bs            string                 `protobuf:"bytes,2,opt,name=bs,proto3" json:"bs,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderID       string                 `protobuf:"bytes,5,opt,name=orderID,proto3" json:"orderID,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrderOrder) Reset() {
	*x = SendOrderOrder{}
	mi := &file_streams_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrderOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderOrder) ProtoMessage() {}

func (x *SendOrderOrder) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderOrder.ProtoReflect.Descriptor instead.
func (*SendOrderOrder) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{14}
}

func (x *SendOrderOrder) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *SendOrderOrder) GetBs() string {
	if x != nil {
		return x.Bs
	}
	return ""
}

func (x *SendOrderOrder) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SendOrderOrder) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SendOrderOrder) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *SendOrderOrder) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// --- deltaOne.strategies (typed state/config) ---
type StrategyState struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Status                 string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TheoreticalPrice       string                 `protobuf:"bytes,2,opt,name=theoreticalPrice,proto3" json:"theoreticalPrice,omitempty"`
	Delta                  string                 `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	PrimaryQty             string                 `protobuf:"bytes,4,opt,name=primaryQty,proto3" json:"primaryQty,omitempty"`
	HedgeQty               string                 `protobuf:"bytes,5,opt,name=hedgeQty,proto3" json:"hedgeQty,omitempty"`
	AutoHedge              string                 `protobuf:"bytes,6,opt,name=autoHedge,proto3" json:"autoHedge,omitempty"`
	LastRefillBuyTime      string                 `protobuf:"bytes,7,opt,name=lastRefillBuyTime,proto3" json:"lastRefillBuyTime,omitempty"`
	LastRefillSellTime     string                 `protobuf:"bytes,8,opt,name=lastRefillSellTime,proto3" json:"lastRefillSellTime,omitempty"`
	LastFillReduceBuyTime  string                 `protobuf:"bytes,9,opt,name=lastFillReduceBuyTime,proto3" json:"lastFillReduceBuyTime,omitempty"`
	LastFillReduceSellTime string                 `protobuf:"bytes,10,opt,name=lastFillReduceSellTime,proto3" json:"lastFillReduceSellTime,omitempty"`
	LastUpdate             string                 `protobuf:"bytes,11,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StrategyState) Reset() {
	*x = StrategyState{}
	mi := &file_streams_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyState) ProtoMessage() {}

func (x *StrategyState) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyState.ProtoReflect.Descriptor instead.
func (*StrategyState) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{15}
}

func (x *StrategyState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StrategyState) GetTheoreticalPrice() string {
	if x != nil {
		return x.TheoreticalPrice
	}
	return ""
}

func (x *StrategyState) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *StrategyState) GetPrimaryQty() string {
	if x != nil {
		return x.PrimaryQty
	}
	return ""
}

func (x *StrategyState) GetHedgeQty() string {
	if x != nil {
		return x.HedgeQty
	}
	return ""
}

func (x *StrategyState) GetAutoHedge() string {
	if x != nil {
		return x.AutoHedge
	}
	return ""
}

func (x *StrategyState) GetLastRefillBuyTime() string {
	if x != nil {
		return x.LastRefillBuyTime
	}
	return ""
}

func (x *StrategyState) GetLastRefillSellTime() string {
	if x != nil {
		return x.LastRefillSellTime
	}
	return ""
}

func (x *StrategyState) GetLastFillReduceBuyTime() string {
	if x != nil {
		return x.LastFillReduceBuyTime
	}
	return ""
}

func (x *StrategyState) GetLastFillReduceSellTime() string {
	if x != nil {
		return x.LastFillReduceSellTime
	}
	return ""
}

func (x *StrategyState) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

type StrategyConfig struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Id                               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsActive                         bool                   `protobuf:"varint,3,opt,name=isActive,proto3" json:"isActive,omitempty"`
	PrimaryInstrument                string                 `protobuf:"bytes,4,opt,name=primaryInstrument,proto3" json:"primaryInstrument,omitempty"`
	HedgeInstrument                  string                 `protobuf:"bytes,5,opt,name=hedgeInstrument,proto3" json:"hedgeInstrument,omitempty"`
	MarketMakingMode                 string                 `protobuf:"bytes,6,opt,name=marketMakingMode,proto3" json:"marketMakingMode,omitempty"`
	MarketMakingSide                 string                 `protobuf:"bytes,7,opt,name=marketMakingSide,proto3" json:"marketMakingSide,omitempty"`
	StrategyMode                     string                 `protobuf:"bytes,8,opt,name=strategyMode,proto3" json:"strategyMode,omitempty"`
	BuyQuantity                      int32                  `protobuf:"varint,9,opt,name=buyQuantity,proto3" json:"buyQuantity,omitempty"`
	SellQuantity                     int32                  `protobuf:"varint,10,opt,name=sellQuantity,proto3" json:"sellQuantity,omitempty"`
	RefillStep                       int32                  `protobuf:"varint,11,opt,name=refillStep,proto3" json:"refillStep,omitempty"`
	RefillPeriod                     int32                  `protobuf:"varint,12,opt,name=refillPeriod,proto3" json:"refillPeriod,omitempty"`
	PriceSensitivity                 float64                `protobuf:"fixed64,13,opt,name=priceSensitivity,proto3" json:"priceSensitivity,omitempty"`
	AutomaticHedge                   bool                   `protobuf:"varint,14,opt,name=automaticHedge,proto3" json:"automaticHedge,omitempty"`
	HedgePrice                       string                 `protobuf:"bytes,15,opt,name=hedgePrice,proto3" json:"hedgePrice,omitempty"`
	HedgePercentOffset               float64                `protobuf:"fixed64,16,opt,name=hedgePercentOffset,proto3" json:"hedgePercentOffset,omitempty"`
	HedgeTickOffset                  int32                  `protobuf:"varint,17,opt,name=hedgeTickOffset,proto3" json:"hedgeTickOffset,omitempty"`
	HedgeSendThreshold               int32                  `protobuf:"varint,18,opt,name=hedgeSendThreshold,proto3" json:"hedgeSendThreshold,omitempty"`
	HedgeRoundingThreshold           float64                `protobuf:"fixed64,19,opt,name=hedgeRoundingThreshold,proto3" json:"hedgeRoundingThreshold,omitempty"`
	StopLossEnabled                  bool                   `protobuf:"varint,20,opt,name=stopLossEnabled,proto3" json:"stopLossEnabled,omitempty"`
	StopLossUnit                     string                 `protobuf:"bytes,21,opt,name=stopLossUnit,proto3" json:"stopLossUnit,omitempty"`
	StopLossPrice                    string                 `protobuf:"bytes,22,opt,name=stopLossPrice,proto3" json:"stopLossPrice,omitempty"`
	StopLossMarginValue              float64                `protobuf:"fixed64,23,opt,name=stopLossMarginValue,proto3" json:"stopLossMarginValue,omitempty"`
	StopLossMarginTick               int32                  `protobuf:"varint,24,opt,name=stopLossMarginTick,proto3" json:"stopLossMarginTick,omitempty"`
	MaxShiftPrimary                  float64                `protobuf:"fixed64,25,opt,name=maxShiftPrimary,proto3" json:"maxShiftPrimary,omitempty"`
	MaxShiftTypePrimary              string                 `protobuf:"bytes,26,opt,name=maxShiftTypePrimary,proto3" json:"maxShiftTypePrimary,omitempty"`
	MaxDailyBuyPrimary               int32                  `protobuf:"varint,27,opt,name=maxDailyBuyPrimary,proto3" json:"maxDailyBuyPrimary,omitempty"`
	MaxDailySellPrimary              int32                  `protobuf:"varint,28,opt,name=maxDailySellPrimary,proto3" json:"maxDailySellPrimary,omitempty"`
	SpreadUnit                       string                 `protobuf:"bytes,29,opt,name=spreadUnit,proto3" json:"spreadUnit,omitempty"`
	SpreadValue                      float64                `protobuf:"fixed64,30,opt,name=spreadValue,proto3" json:"spreadValue,omitempty"`
	SpreadDistribution               string                 `protobuf:"bytes,31,opt,name=spreadDistribution,proto3" json:"spreadDistribution,omitempty"`
	BidMarginUnit                    string                 `protobuf:"bytes,32,opt,name=bidMarginUnit,proto3" json:"bidMarginUnit,omitempty"`
	BidMarginValue                   float64                `protobuf:"fixed64,33,opt,name=bidMarginValue,proto3" json:"bidMarginValue,omitempty"`
	BidMarginTick                    int32                  `protobuf:"varint,34,opt,name=bidMarginTick,proto3" json:"bidMarginTick,omitempty"`
	AskMarginUnit                    string                 `protobuf:"bytes,35,opt,name=askMarginUnit,proto3" json:"askMarginUnit,omitempty"`
	AskMarginValue                   float64                `protobuf:"fixed64,36,opt,name=askMarginValue,proto3" json:"askMarginValue,omitempty"`
	AskMarginTick                    int32                  `protobuf:"varint,37,opt,name=askMarginTick,proto3" json:"askMarginTick,omitempty"`
	PrimaryPriceUnderlyingInstrument string                 `protobuf:"bytes,38,opt,name=primaryPriceUnderlyingInstrument,proto3" json:"primaryPriceUnderlyingInstrument,omitempty"`
	PrimaryPriceXSource              string                 `protobuf:"bytes,39,opt,name=primaryPriceXSource,proto3" json:"primaryPriceXSource,omitempty"`
	PrimaryPriceA                    float64                `protobuf:"fixed64,40,opt,name=primaryPriceA,proto3" json:"primaryPriceA,omitempty"`
	PrimaryPriceB                    float64                `protobuf:"fixed64,41,opt,name=primaryPriceB,proto3" json:"primaryPriceB,omitempty"`
	HedgeQuantityA                   float64                `protobuf:"fixed64,42,opt,name=hedgeQuantityA,proto3" json:"hedgeQuantityA,omitempty"`
	CreatedAt                        string                 `protobuf:"bytes,43,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt                        string                 `protobuf:"bytes,44,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *StrategyConfig) Reset() {
	*x = StrategyConfig{}
	mi := &file_streams_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyConfig) ProtoMessage() {}

func (x *StrategyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyConfig.ProtoReflect.Descriptor instead.
func (*StrategyConfig) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{16}
}

func (x *StrategyConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StrategyConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StrategyConfig) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *StrategyConfig) GetPrimaryInstrument() string {
	if x != nil {
		return x.PrimaryInstrument
	}
	return ""
}

func (x *StrategyConfig) GetHedgeInstrument() string {
	if x != nil {
		return x.HedgeInstrument
	}
	return ""
}

func (x *StrategyConfig) GetMarketMakingMode() string {
	if x != nil {
		return x.MarketMakingMode
	}
	return ""
}

func (x *StrategyConfig) GetMarketMakingSide() string {
	if x != nil {
		return x.MarketMakingSide
	}
	return ""
}

func (x *StrategyConfig) GetStrategyMode() string {
	if x != nil {
		return x.StrategyMode
	}
	return ""
}

func (x *StrategyConfig) GetBuyQuantity() int32 {
	if x != nil {
		return x.BuyQuantity
	}
	return 0
}

func (x *StrategyConfig) GetSellQuantity() int32 {
	if x != nil {
		return x.SellQuantity
	}
	return 0
}

func (x *StrategyConfig) GetRefillStep() int32 {
	if x != nil {
		return x.RefillStep
	}
	return 0
}

func (x *StrategyConfig) GetRefillPeriod() int32 {
	if x != nil {
		return x.RefillPeriod
	}
	return 0
}

func (x *StrategyConfig) GetPriceSensitivity() float64 {
	if x != nil {
		return x.PriceSensitivity
	}
	return 0
}

func (x *StrategyConfig) GetAutomaticHedge() bool {
	if x != nil {
		return x.AutomaticHedge
	}
	return false
}

func (x *StrategyConfig) GetHedgePrice() string {
	if x != nil {
		return x.HedgePrice
	}
	return ""
}

func (x *StrategyConfig) GetHedgePercentOffset() float64 {
	if x != nil {
		return x.HedgePercentOffset
	}
	return 0
}

func (x *StrategyConfig) GetHedgeTickOffset() int32 {
	if x != nil {
		return x.HedgeTickOffset
	}
	return 0
}

func (x *StrategyConfig) GetHedgeSendThreshold() int32 {
	if x != nil {
		return x.HedgeSendThreshold
	}
	return 0
}

func (x *StrategyConfig) GetHedgeRoundingThreshold() float64 {
	if x != nil {
		return x.HedgeRoundingThreshold
	}
	return 0
}

func (x *StrategyConfig) GetStopLossEnabled() bool {
	if x != nil {
		return x.StopLossEnabled
	}
	return false
}

func (x *StrategyConfig) GetStopLossUnit() string {
	if x != nil {
		return x.StopLossUnit
	}
	return ""
}

func (x *StrategyConfig) GetStopLossPrice() string {
	if x != nil {
		return x.StopLossPrice
	}
	return ""
}

func (x *StrategyConfig) GetStopLossMarginValue() float64 {
	if x != nil {
		return x.StopLossMarginValue
	}
	return 0
}

func (x *StrategyConfig) GetStopLossMarginTick() int32 {
	if x != nil {
		return x.StopLossMarginTick
	}
	return 0
}

func (x *StrategyConfig) GetMaxShiftPrimary() float64 {
	if x != nil {
		return x.MaxShiftPrimary
	}
	return 0
}

func (x *StrategyConfig) GetMaxShiftTypePrimary() string {
	if x != nil {
		return x.MaxShiftTypePrimary
	}
	return ""
}

func (x *StrategyConfig) GetMaxDailyBuyPrimary() int32 {
	if x != nil {
		return x.MaxDailyBuyPrimary
	}
	return 0
}

func (x *StrategyConfig) GetMaxDailySellPrimary() int32 {
	if x != nil {
		return x.MaxDailySellPrimary
	}
	return 0
}

func (x *StrategyConfig) GetSpreadUnit() string {
	if x != nil {
		return x.SpreadUnit
	}
	return ""
}

func (x *StrategyConfig) GetSpreadValue() float64 {
	if x != nil {
		return x.SpreadValue
	}
	return 0
}

func (x *StrategyConfig) GetSpreadDistribution() string {
	if x != nil {
		return x.SpreadDistribution
	}
	return ""
}

func (x *StrategyConfig) GetBidMarginUnit() string {
	if x != nil {
		return x.BidMarginUnit
	}
	return ""
}

func (x *StrategyConfig) GetBidMarginValue() float64 {
	if x != nil {
		return x.BidMarginValue
	}
	return 0
}

func (x *StrategyConfig) GetBidMarginTick() int32 {
	if x != nil {
		return x.BidMarginTick
	}
	return 0
}

func (x *StrategyConfig) GetAskMarginUnit() string {
	if x != nil {
		return x.AskMarginUnit
	}
	return ""
}

func (x *StrategyConfig) GetAskMarginValue() float64 {
	if x != nil {
		return x.AskMarginValue
	}
	return 0
}

func (x *StrategyConfig) GetAskMarginTick() int32 {
	if x != nil {
		return x.AskMarginTick
	}
	return 0
}

func (x *StrategyConfig) GetPrimaryPriceUnderlyingInstrument() string {
	if x != nil {
		return x.PrimaryPriceUnderlyingInstrument
	}
	return ""
}

func (x *StrategyConfig) GetPrimaryPriceXSource() string {
	if x != nil {
		return x.PrimaryPriceXSource
	}
	return ""
}

func (x *StrategyConfig) GetPrimaryPriceA() float64 {
	if x != nil {
		return x.PrimaryPriceA
	}
	return 0
}

func (x *StrategyConfig) GetPrimaryPriceB() float64 {
	if x != nil {
		return x.PrimaryPriceB
	}
	return 0
}

func (x *StrategyConfig) GetHedgeQuantityA() float64 {
	if x != nil {
		return x.HedgeQuantityA
	}
	return 0
}

func (x *StrategyConfig) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StrategyConfig) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type StrategyUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	State         *StrategyState         `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Config        *StrategyConfig        `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyUpdateEvent) Reset() {
	*x = StrategyUpdateEvent{}
	mi := &file_streams_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyUpdateEvent) ProtoMessage() {}

func (x *StrategyUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyUpdateEvent.ProtoReflect.Descriptor instead.
func (*StrategyUpdateEvent) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{17}
}

func (x *StrategyUpdateEvent) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *StrategyUpdateEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StrategyUpdateEvent) GetState() *StrategyState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *StrategyUpdateEvent) GetConfig() *StrategyConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StrategyUpdateEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// --- deltaOne.quotes ---
type QuoteUpdateEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StrategyId       string                 `protobuf:"bytes,1,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	TheoreticalPrice float64                `protobuf:"fixed64,2,opt,name=theoreticalPrice,proto3" json:"theoreticalPrice,omitempty"`
	MarketBid        float64                `protobuf:"fixed64,3,opt,name=marketBid,proto3" json:"marketBid,omitempty"`
	MarketAsk        float64                `protobuf:"fixed64,4,opt,name=marketAsk,proto3" json:"marketAsk,omitempty"`
	AutoBid          float64                `protobuf:"fixed64,5,opt,name=autoBid,proto3" json:"autoBid,omitempty"`
	AutoAsk          float64                `protobuf:"fixed64,6,opt,name=autoAsk,proto3" json:"autoAsk,omitempty"`
	HedgeBid         float64                `protobuf:"fixed64,7,opt,name=hedgeBid,proto3" json:"hedgeBid,omitempty"`
	HedgeAsk         float64                `protobuf:"fixed64,8,opt,name=hedgeAsk,proto3" json:"hedgeAsk,omitempty"`
	Timestamp        string                 `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QuoteUpdateEvent) Reset() {
	*x = QuoteUpdateEvent{}
	mi := &file_streams_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteUpdateEvent) ProtoMessage() {}

func (x *QuoteUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteUpdateEvent.ProtoReflect.Descriptor instead.
func (*QuoteUpdateEvent) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{18}
}

func (x *QuoteUpdateEvent) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *QuoteUpdateEvent) GetTheoreticalPrice() float64 {
	if x != nil {
		return x.TheoreticalPrice
	}
	return 0
}

func (x *QuoteUpdateEvent) GetMarketBid() float64 {
	if x != nil {
		return x.MarketBid
	}
	return 0
}

func (x *QuoteUpdateEvent) GetMarketAsk() float64 {
	if x != nil {
		return x.MarketAsk
	}
	return 0
}

func (x *QuoteUpdateEvent) GetAutoBid() float64 {
	if x != nil {
		return x.AutoBid
	}
	return 0
}

func (x *QuoteUpdateEvent) GetAutoAsk() float64 {
	if x != nil {
		return x.AutoAsk
	}
	return 0
}

func (x *QuoteUpdateEvent) GetHedgeBid() float64 {
	if x != nil {
		return x.HedgeBid
	}
	return 0
}

func (x *QuoteUpdateEvent) GetHedgeAsk() float64 {
	if x != nil {
		return x.HedgeAsk
	}
	return 0
}

func (x *QuoteUpdateEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// --- deltaOne.positions ---
type PositionUpdateEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	StrategyId            string                 `protobuf:"bytes,1,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	PrimaryQty            float64                `protobuf:"fixed64,2,opt,name=primaryQty,proto3" json:"primaryQty,omitempty"`
	PrimaryFilledBuyQty   float64                `protobuf:"fixed64,3,opt,name=primaryFilledBuyQty,proto3" json:"primaryFilledBuyQty,omitempty"`
	PrimaryFilledSellQty  float64                `protobuf:"fixed64,4,opt,name=primaryFilledSellQty,proto3" json:"primaryFilledSellQty,omitempty"`
	PrimaryPendingBuyQty  float64                `protobuf:"fixed64,5,opt,name=primaryPendingBuyQty,proto3" json:"primaryPendingBuyQty,omitempty"`
	PrimaryPendingSellQty float64                `protobuf:"fixed64,6,opt,name=primaryPendingSellQty,proto3" json:"primaryPendingSellQty,omitempty"`
	HedgeQty              float64                `protobuf:"fixed64,7,opt,name=hedgeQty,proto3" json:"hedgeQty,omitempty"`
	HedgeFilledBuyQty     float64                `protobuf:"fixed64,8,opt,name=hedgeFilledBuyQty,proto3" json:"hedgeFilledBuyQty,omitempty"`
	HedgeFilledSellQty    float64                `protobuf:"fixed64,9,opt,name=hedgeFilledSellQty,proto3" json:"hedgeFilledSellQty,omitempty"`
	HedgePendingBuyQty    float64                `protobuf:"fixed64,10,opt,name=hedgePendingBuyQty,proto3" json:"hedgePendingBuyQty,omitempty"`
	HedgePendingSellQty   float64                `protobuf:"fixed64,11,opt,name=hedgePendingSellQty,proto3" json:"hedgePendingSellQty,omitempty"`
	Delta                 float64                `protobuf:"fixed64,12,opt,name=delta,proto3" json:"delta,omitempty"`
	Pnl                   float64                `protobuf:"fixed64,13,opt,name=pnl,proto3" json:"pnl,omitempty"`
	Timestamp             string                 `protobuf:"bytes,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PositionUpdateEvent) Reset() {
	*x = PositionUpdateEvent{}
	mi := &file_streams_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionUpdateEvent) ProtoMessage() {}

func (x *PositionUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionUpdateEvent.ProtoReflect.Descriptor instead.
func (*PositionUpdateEvent) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{19}
}

func (x *PositionUpdateEvent) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *PositionUpdateEvent) GetPrimaryQty() float64 {
	if x != nil {
		return x.PrimaryQty
	}
	return 0
}

func (x *PositionUpdateEvent) GetPrimaryFilledBuyQty() float64 {
	if x != nil {
		return x.PrimaryFilledBuyQty
	}
	return 0
}

func (x *PositionUpdateEvent) GetPrimaryFilledSellQty() float64 {
	if x != nil {
		return x.PrimaryFilledSellQty
	}
	return 0
}

func (x *PositionUpdateEvent) GetPrimaryPendingBuyQty() float64 {
	if x != nil {
		return x.PrimaryPendingBuyQty
	}
	return 0
}

func (x *PositionUpdateEvent) GetPrimaryPendingSellQty() float64 {
	if x != nil {
		return x.PrimaryPendingSellQty
	}
	return 0
}

func (x *PositionUpdateEvent) GetHedgeQty() float64 {
	if x != nil {
		return x.HedgeQty
	}
	return 0
}

func (x *PositionUpdateEvent) GetHedgeFilledBuyQty() float64 {
	if x != nil {
		return x.HedgeFilledBuyQty
	}
	return 0
}

func (x *PositionUpdateEvent) GetHedgeFilledSellQty() float64 {
	if x != nil {
		return x.HedgeFilledSellQty
	}
	return 0
}

func (x *PositionUpdateEvent) GetHedgePendingBuyQty() float64 {
	if x != nil {
		return x.HedgePendingBuyQty
	}
	return 0
}

func (x *PositionUpdateEvent) GetHedgePendingSellQty() float64 {
	if x != nil {
		return x.HedgePendingSellQty
	}
	return 0
}

func (x *PositionUpdateEvent) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *PositionUpdateEvent) GetPnl() float64 {
	if x != nil {
		return x.Pnl
	}
	return 0
}

func (x *PositionUpdateEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// --- deltaOne.risk ---
type RiskUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	Delta         float64                `protobuf:"fixed64,2,opt,name=delta,proto3" json:"delta,omitempty"`
	FilledBuyQty  float64                `protobuf:"fixed64,3,opt,name=filledBuyQty,proto3" json:"filledBuyQty,omitempty"`
	FilledSellQty float64                `protobuf:"fixed64,4,opt,name=filledSellQty,proto3" json:"filledSellQty,omitempty"`
	MaxDailyBuy   int32                  `protobuf:"varint,5,opt,name=maxDailyBuy,proto3" json:"maxDailyBuy,omitempty"`
	MaxDailySell  int32                  `protobuf:"varint,6,opt,name=maxDailySell,proto3" json:"maxDailySell,omitempty"`
	RiskStatus    string                 `protobuf:"bytes,7,opt,name=riskStatus,proto3" json:"riskStatus,omitempty"`
	Timestamp     string                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskUpdateEvent) Reset() {
	*x = RiskUpdateEvent{}
	mi := &file_streams_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskUpdateEvent) ProtoMessage() {}

func (x *RiskUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streams_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskUpdateEvent.ProtoReflect.Descriptor instead.
func (*RiskUpdateEvent) Descriptor() ([]byte, []int) {
	return file_streams_proto_rawDescGZIP(), []int{20}
}

func (x *RiskUpdateEvent) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *RiskUpdateEvent) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *RiskUpdateEvent) GetFilledBuyQty() float64 {
	if x != nil {
		return x.FilledBuyQty
	}
	return 0
}

func (x *RiskUpdateEvent) GetFilledSellQty() float64 {
	if x != nil {
		return x.FilledSellQty
	}
	return 0
}

func (x *RiskUpdateEvent) GetMaxDailyBuy() int32 {
	if x != nil {
		return x.MaxDailyBuy
	}
	return 0
}

func (x *RiskUpdateEvent) GetMaxDailySell() int32 {
	if x != nil {
		return x.MaxDailySell
	}
	return 0
}

func (x *RiskUpdateEvent) GetRiskStatus() string {
	if x != nil {
		return x.RiskStatus
	}
	return ""
}

func (x *RiskUpdateEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_streams_proto protoreflect.FileDescriptor

const file_streams_proto_rawDesc = "" +
	"\n" +
	"\rstreams.proto\x12\x02pb\"\xc5\x02\n" +
	"\x11OrderEventPayload\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x0e\n" +
	"\x02bs\x18\x02 \x01(\tR\x02bs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x18\n" +
	"\apending\x18\x06 \x01(\x01R\apending\x12\x16\n" +
	"\x06filled\x18\a \x01(\x01R\x06filled\x12\x1a\n" +
	"\bavgPrice\x18\b \x01(\x01R\bavgPrice\x12\x18\n" +
	"\aorderID\x18\t \x01(\tR\aorderID\x12\"\n" +
	"\fmessageError\x18\n" +
	" \x01(\tR\fmessageError\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x1a\n" +
	"\bbasketID\x18\f \x01(\tR\bbasketID\"m\n" +
	"\x11TradeEventPayload\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\tR\x06volume\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\"E\n" +
	"\vActiveRange\x12\x1a\n" +
	"\bminPrice\x18\x01 \x01(\x01R\bminPrice\x12\x1a\n" +
	"\bmaxPrice\x18\x02 \x01(\x01R\bmaxPrice\"\xc8\x01\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\"\n" +
	"\fmarketBidQty\x18\x02 \x01(\x01R\fmarketBidQty\x12\"\n" +
	"\fmarketAskQty\x18\x03 \x01(\x01R\fmarketAskQty\x12,\n" +
	"\x11userPendingBuyQty\x18\x04 \x01(\x01R\x11userPendingBuyQty\x12.\n" +
	"\x12userPendingSellQty\x18\x05 \x01(\x01R\x12userPendingSellQty\"\xd2\x01\n" +
	"\x0fOrderbookUpdate\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x14\n" +
	"\x05floor\x18\x02 \x01(\x01R\x05floor\x12\x18\n" +
	"\aceiling\x18\x03 \x01(\x01R\aceiling\x12\x1c\n" +
	"\tpriceStep\x18\x04 \x01(\x01R\tpriceStep\x121\n" +
	"\vactiveRange\x18\x05 \x01(\v2\x0f.pb.ActiveRangeR\vactiveRange\x12&\n" +
	"\x06levels\x18\x06 \x03(\v2\x0e.pb.PriceLevelR\x06levels\"\x95\x02\n" +
	"\x11PortfolioPLResult\x12\x1c\n" +
	"\tfilledBuy\x18\x01 \x01(\x01R\tfilledBuy\x12\x1e\n" +
	"\n" +
	"filledSell\x18\x02 \x01(\x01R\n" +
	"filledSell\x12\x1c\n" +
	"\tnetFilled\x18\x03 \x01(\x01R\tnetFilled\x12\x1e\n" +
	"\n" +
	"pendingBuy\x18\x04 \x01(\x01R\n" +
	"pendingBuy\x12 \n" +
	"\vpendingSell\x18\x05 \x01(\x01R\vpendingSell\x12\x1e\n" +
	"\n" +
	"netPending\x18\x06 \x01(\x01R\n" +
	"netPending\x12\x10\n" +
	"\x03fee\x18\a \x01(\x01R\x03fee\x12\x0e\n" +
	"\x02pl\x18\b \x01(\x01R\x02pl\x12 \n" +
	"\vcapitalUsed\x18\t \x01(\x01R\vcapitalUsed\"\xe6\x01\n" +
	"\x12PortfolioPLPayload\x12+\n" +
	"\x05stock\x18\x01 \x01(\v2\x15.pb.PortfolioPLResultR\x05stock\x12'\n" +
	"\x03etf\x18\x02 \x01(\v2\x15.pb.PortfolioPLResultR\x03etf\x12-\n" +
	"\x06future\x18\x03 \x01(\v2\x15.pb.PortfolioPLResultR\x06future\x12+\n" +
	"\x05total\x18\x04 \x01(\v2\x15.pb.PortfolioPLResultR\x05total\x12\x1e\n" +
	"\n" +
	"lastUpdate\x18\x05 \x01(\x03R\n" +
	"lastUpdate\"\xda\b\n" +
	"\n" +
	"LegsPLData\x12\"\n" +
	"\ffilledBuyQty\x18\x01 \x01(\x01R\ffilledBuyQty\x12&\n" +
	"\x0efilledBuyValue\x18\x02 \x01(\x01R\x0efilledBuyValue\x12$\n" +
	"\rfilledSellQty\x18\x03 \x01(\x01R\rfilledSellQty\x12(\n" +
	"\x0ffilledSellValue\x18\x04 \x01(\x01R\x0ffilledSellValue\x12$\n" +
	"\rpendingBuyQty\x18\x05 \x01(\x01R\rpendingBuyQty\x12(\n" +
	"\x0fpendingBuyValue\x18\x06 \x01(\x01R\x0fpendingBuyValue\x12&\n" +
	"\x0ependingSellQty\x18\a \x01(\x01R\x0ependingSellQty\x12*\n" +
	"\x10pendingSellValue\x18\b \x01(\x01R\x10pendingSellValue\x12\x10\n" +
	"\x03fee\x18\t \x01(\x01R\x03fee\x12\x1a\n" +
	"\bunitCost\x18\n" +
	" \x01(\x01R\bunitCost\x12\"\n" +
	"\funrealizedPL\x18\v \x01(\x01R\funrealizedPL\x12\x1e\n" +
	"\n" +
	"realizedPL\x18\f \x01(\x01R\n" +
	"realizedPL\x12\x18\n" +
	"\atotalPL\x18\r \x01(\x01R\atotalPL\x12\x1c\n" +
	"\ttradingPL\x18\x0e \x01(\x01R\ttradingPL\x12\"\n" +
	"\fbeginningQty\x18\x0f \x01(\x01R\fbeginningQty\x12 \n" +
	"\vtradableQty\x18\x10 \x01(\x01R\vtradableQty\x122\n" +
	"\x14beginningTradableQty\x18\x11 \x01(\x01R\x14beginningTradableQty\x12\x1c\n" +
	"\tdueBuyQty\x18\x12 \x01(\x01R\tdueBuyQty\x12 \n" +
	"\vt1CreateQty\x18\x13 \x01(\x01R\vt1CreateQty\x12,\n" +
	"\x11unsettledStockQty\x18\x14 \x01(\x01R\x11unsettledStockQty\x12\x14\n" +
	"\x05t1Qty\x18\x15 \x01(\x01R\x05t1Qty\x12\x1c\n" +
	"\tcreateQty\x18\x16 \x01(\x01R\tcreateQty\x12 \n" +
	"\vcreateValue\x18\x17 \x01(\x01R\vcreateValue\x12\x1c\n" +
	"\tredeemQty\x18\x18 \x01(\x01R\tredeemQty\x12 \n" +
	"\vredeemValue\x18\x19 \x01(\x01R\vredeemValue\x12(\n" +
	"\x0ffailedCreateQty\x18\x1a \x01(\x01R\x0ffailedCreateQty\x12,\n" +
	"\x11failedCreateValue\x18\x1b \x01(\x01R\x11failedCreateValue\x12(\n" +
	"\x0ffailedRedeemQty\x18\x1c \x01(\x01R\x0ffailedRedeemQty\x12,\n" +
	"\x11failedRedeemValue\x18\x1d \x01(\x01R\x11failedRedeemValue\x12 \n" +
	"\vdividendQty\x18\x1e \x01(\x01R\vdividendQty\x12\x12\n" +
	"\x04cash\x18\x1f \x01(\x01R\x04cash\"}\n" +
	"\rLegsPLPayload\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x1c\n" +
	"\tassetType\x18\x02 \x01(\tR\tassetType\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.pb.LegsPLDataR\x04data\x12\x12\n" +
	"\x04asOf\x18\x04 \x01(\x03R\x04asOf\"\xf7\x03\n" +
	"\vBasketState\x12\x12\n" +
	"\x04side\x18\x01 \x01(\tR\x04side\x12\"\n" +
	"\fbasketTarget\x18\x02 \x01(\x01R\fbasketTarget\x12&\n" +
	"\x0ebasketExecuted\x18\x03 \x01(\x01R\x0ebasketExecuted\x12$\n" +
	"\rbasketInitial\x18\x04 \x01(\x01R\rbasketInitial\x12$\n" +
	"\rfuturesTarget\x18\x05 \x01(\x01R\rfuturesTarget\x12(\n" +
	"\x0ffuturesExecuted\x18\x06 \x01(\x01R\x0ffuturesExecuted\x12&\n" +
	"\x0efuturesInitial\x18\a \x01(\x01R\x0efuturesInitial\x12 \n" +
	"\vbasisTarget\x18\b \x01(\x01R\vbasisTarget\x12\x1a\n" +
	"\bbasisNow\x18\t \x01(\x01R\bbasisNow\x12\"\n" +
	"\fbasisInitial\x18\n" +
	" \x01(\x01R\fbasisInitial\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"basketName\x18\f \x01(\tR\n" +
	"basketName\x12\x1a\n" +
	"\bbasketID\x18\r \x01(\tR\bbasketID\x12\x1c\n" +
	"\tcreatedAt\x18\x0e \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06zscore\x18\x0f \x01(\x01R\x06zscore\"\x97\x01\n" +
	"\tOrderInfo\x12\x0e\n" +
	"\x02bs\x18\x01 \x01(\tR\x02bs\x12\x18\n" +
	"\aorderID\x18\x02 \x01(\tR\aorderID\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x16\n" +
	"\x06ticker\x18\x06 \x01(\tR\x06ticker\"Z\n" +
	"\x13BasketUpdatePayload\x12\x1a\n" +
	"\bbasketID\x18\x01 \x01(\tR\bbasketID\x12'\n" +
	"\x06basket\x18\x02 \x01(\v2\x0f.pb.BasketStateR\x06basket\"\x7f\n" +
	"\x11BasketDataPayload\x12\x1a\n" +
	"\bbasketID\x18\x01 \x01(\tR\bbasketID\x12'\n" +
	"\x06basket\x18\x02 \x01(\v2\x0f.pb.BasketStateR\x06basket\x12%\n" +
	"\x06orders\x18\x03 \x03(\v2\r.pb.OrderInfoR\x06orders\"\x8e\x01\n" +
	"\x10SendOrderCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bbasketID\x18\x02 \x01(\tR\bbasketID\x12\x1a\n" +
	"\bslowMode\x18\x03 \x01(\bR\bslowMode\x12*\n" +
	"\x06orders\x18\x04 \x03(\v2\x12.pb.SendOrderOrderR\x06orders\"\x9c\x01\n" +
	"\x0eSendOrderOrder\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x0e\n" +
	"\x02bs\x18\x02 \x01(\tR\x02bs\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x18\n" +
	"\aorderID\x18\x05 \x01(\tR\aorderID\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\"\xaf\x03\n" +
	"\rStrategyState\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12*\n" +
	"\x10theoreticalPrice\x18\x02 \x01(\tR\x10theoreticalPrice\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\tR\x05delta\x12\x1e\n" +
	"\n" +
	"primaryQty\x18\x04 \x01(\tR\n" +
	"primaryQty\x12\x1a\n" +
	"\bhedgeQty\x18\x05 \x01(\tR\bhedgeQty\x12\x1c\n" +
	"\tautoHedge\x18\x06 \x01(\tR\tautoHedge\x12,\n" +
	"\x11lastRefillBuyTime\x18\a \x01(\tR\x11lastRefillBuyTime\x12.\n" +
	"\x12lastRefillSellTime\x18\b \x01(\tR\x12lastRefillSellTime\x124\n" +
	"\x15lastFillReduceBuyTime\x18\t \x01(\tR\x15lastFillReduceBuyTime\x126\n" +
	"\x16lastFillReduceSellTime\x18\n" +
	" \x01(\tR\x16lastFillReduceSellTime\x12\x1e\n" +
	"\n" +
	"lastUpdate\x18\v \x01(\tR\n" +
	"lastUpdate\"\x80\x0e\n" +
	"\x0eStrategyConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bisActive\x18\x03 \x01(\bR\bisActive\x12,\n" +
	"\x11primaryInstrument\x18\x04 \x01(\tR\x11primaryInstrument\x12(\n" +
	"\x0fhedgeInstrument\x18\x05 \x01(\tR\x0fhedgeInstrument\x12*\n" +
	"\x10marketMakingMode\x18\x06 \x01(\tR\x10marketMakingMode\x12*\n" +
	"\x10marketMakingSide\x18\a \x01(\tR\x10marketMakingSide\x12\"\n" +
	"\fstrategyMode\x18\b \x01(\tR\fstrategyMode\x12 \n" +
	"\vbuyQuantity\x18\t \x01(\x05R\vbuyQuantity\x12\"\n" +
	"\fsellQuantity\x18\n" +
	" \x01(\x05R\fsellQuantity\x12\x1e\n" +
	"\n" +
	"refillStep\x18\v \x01(\x05R\n" +
	"refillStep\x12\"\n" +
	"\frefillPeriod\x18\f \x01(\x05R\frefillPeriod\x12*\n" +
	"\x10priceSensitivity\x18\r \x01(\x01R\x10priceSensitivity\x12&\n" +
	"\x0eautomaticHedge\x18\x0e \x01(\bR\x0eautomaticHedge\x12\x1e\n" +
	"\n" +
	"hedgePrice\x18\x0f \x01(\tR\n" +
	"hedgePrice\x12.\n" +
	"\x12hedgePercentOffset\x18\x10 \x01(\x01R\x12hedgePercentOffset\x12(\n" +
	"\x0fhedgeTickOffset\x18\x11 \x01(\x05R\x0fhedgeTickOffset\x12.\n" +
	"\x12hedgeSendThreshold\x18\x12 \x01(\x05R\x12hedgeSendThreshold\x126\n" +
	"\x16hedgeRoundingThreshold\x18\x13 \x01(\x01R\x16hedgeRoundingThreshold\x12(\n" +
	"\x0fstopLossEnabled\x18\x14 \x01(\bR\x0fstopLossEnabled\x12\"\n" +
	"\fstopLossUnit\x18\x15 \x01(\tR\fstopLossUnit\x12$\n" +
	"\rstopLossPrice\x18\x16 \x01(\tR\rstopLossPrice\x120\n" +
	"\x13stopLossMarginValue\x18\x17 \x01(\x01R\x13stopLossMarginValue\x12.\n" +
	"\x12stopLossMarginTick\x18\x18 \x01(\x05R\x12stopLossMarginTick\x12(\n" +
	"\x0fmaxShiftPrimary\x18\x19 \x01(\x01R\x0fmaxShiftPrimary\x120\n" +
	"\x13maxShiftTypePrimary\x18\x1a \x01(\tR\x13maxShiftTypePrimary\x12.\n" +
	"\x12maxDailyBuyPrimary\x18\x1b \x01(\x05R\x12maxDailyBuyPrimary\x120\n" +
	"\x13maxDailySellPrimary\x18\x1c \x01(\x05R\x13maxDailySellPrimary\x12\x1e\n" +
	"\n" +
	"spreadUnit\x18\x1d \x01(\tR\n" +
	"spreadUnit\x12 \n" +
	"\vspreadValue\x18\x1e \x01(\x01R\vspreadValue\x12.\n" +
	"\x12spreadDistribution\x18\x1f \x01(\tR\x12spreadDistribution\x12$\n" +
	"\rbidMarginUnit\x18  \x01(\tR\rbidMarginUnit\x12&\n" +
	"\x0ebidMarginValue\x18! \x01(\x01R\x0ebidMarginValue\x12$\n" +
	"\rbidMarginTick\x18\" \x01(\x05R\rbidMarginTick\x12$\n" +
	"\raskMarginUnit\x18# \x01(\tR\raskMarginUnit\x12&\n" +
	"\x0easkMarginValue\x18$ \x01(\x01R\x0easkMarginValue\x12$\n" +
	"\raskMarginTick\x18% \x01(\x05R\raskMarginTick\x12J\n" +
	" primaryPriceUnderlyingInstrument\x18& \x01(\tR primaryPriceUnderlyingInstrument\x120\n" +
	"\x13primaryPriceXSource\x18' \x01(\tR\x13primaryPriceXSource\x12$\n" +
	"\rprimaryPriceA\x18( \x01(\x01R\rprimaryPriceA\x12$\n" +
	"\rprimaryPriceB\x18) \x01(\x01R\rprimaryPriceB\x12&\n" +
	"\x0ehedgeQuantityA\x18* \x01(\x01R\x0ehedgeQuantityA\x12\x1c\n" +
	"\tcreatedAt\x18+ \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18, \x01(\tR\tupdatedAt\"\xc0\x01\n" +
	"\x13StrategyUpdateEvent\x12\x1e\n" +
	"\n" +
	"strategyId\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x05state\x18\x03 \x01(\v2\x11.pb.StrategyStateR\x05state\x12*\n" +
	"\x06config\x18\x04 \x01(\v2\x12.pb.StrategyConfigR\x06config\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"\xa4\x02\n" +
	"\x10QuoteUpdateEvent\x12\x1e\n" +
	"\n" +
	"strategyId\x18\x01 \x01(\tR\n" +
	"strategyId\x12*\n" +
	"\x10theoreticalPrice\x18\x02 \x01(\x01R\x10theoreticalPrice\x12\x1c\n" +
	"\tmarketBid\x18\x03 \x01(\x01R\tmarketBid\x12\x1c\n" +
	"\tmarketAsk\x18\x04 \x01(\x01R\tmarketAsk\x12\x18\n" +
	"\aautoBid\x18\x05 \x01(\x01R\aautoBid\x12\x18\n" +
	"\aautoAsk\x18\x06 \x01(\x01R\aautoAsk\x12\x1a\n" +
	"\bhedgeBid\x18\a \x01(\x01R\bhedgeBid\x12\x1a\n" +
	"\bhedgeAsk\x18\b \x01(\x01R\bhedgeAsk\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\tR\ttimestamp\"\xc7\x04\n" +
	"\x13PositionUpdateEvent\x12\x1e\n" +
	"\n" +
	"strategyId\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x1e\n" +
	"\n" +
	"primaryQty\x18\x02 \x01(\x01R\n" +
	"primaryQty\x120\n" +
	"\x13primaryFilledBuyQty\x18\x03 \x01(\x01R\x13primaryFilledBuyQty\x122\n" +
	"\x14primaryFilledSellQty\x18\x04 \x01(\x01R\x14primaryFilledSellQty\x122\n" +
	"\x14primaryPendingBuyQty\x18\x05 \x01(\x01R\x14primaryPendingBuyQty\x124\n" +
	"\x15primaryPendingSellQty\x18\x06 \x01(\x01R\x15primaryPendingSellQty\x12\x1a\n" +
	"\bhedgeQty\x18\a \x01(\x01R\bhedgeQty\x12,\n" +
	"\x11hedgeFilledBuyQty\x18\b \x01(\x01R\x11hedgeFilledBuyQty\x12.\n" +
	"\x12hedgeFilledSellQty\x18\t \x01(\x01R\x12hedgeFilledSellQty\x12.\n" +
	"\x12hedgePendingBuyQty\x18\n" +
	" \x01(\x01R\x12hedgePendingBuyQty\x120\n" +
	"\x13hedgePendingSellQty\x18\v \x01(\x01R\x13hedgePendingSellQty\x12\x14\n" +
	"\x05delta\x18\f \x01(\x01R\x05delta\x12\x10\n" +
	"\x03pnl\x18\r \x01(\x01R\x03pnl\x12\x1c\n" +
	"\ttimestamp\x18\x0e \x01(\tR\ttimestamp\"\x95\x02\n" +
	"\x0fRiskUpdateEvent\x12\x1e\n" +
	"\n" +
	"strategyId\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x01R\x05delta\x12\"\n" +
	"\ffilledBuyQty\x18\x03 \x01(\x01R\ffilledBuyQty\x12$\n" +
	"\rfilledSellQty\x18\x04 \x01(\x01R\rfilledSellQty\x12 \n" +
	"\vmaxDailyBuy\x18\x05 \x01(\x05R\vmaxDailyBuy\x12\"\n" +
	"\fmaxDailySell\x18\x06 \x01(\x05R\fmaxDailySell\x12\x1e\n" +
	"\n" +
	"riskStatus\x18\a \x01(\tR\n" +
	"riskStatus\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestampB!Z\x1fgithub.com/trading-system/pb;pbb\x06proto3"

var (
	file_streams_proto_rawDescOnce sync.Once
	file_streams_proto_rawDescData []byte
)

func file_streams_proto_rawDescGZIP() []byte {
	file_streams_proto_rawDescOnce.Do(func() {
		file_streams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streams_proto_rawDesc), len(file_streams_proto_rawDesc)))
	})
	return file_streams_proto_rawDescData
}

var file_streams_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_streams_proto_goTypes = []any{
	(*OrderEventPayload)(nil),   // 0: pb.OrderEventPayload
	(*TradeEventPayload)(nil),   // 1: pb.TradeEventPayload
	(*ActiveRange)(nil),         // 2: pb.ActiveRange
	(*PriceLevel)(nil),          // 3: pb.PriceLevel
	(*OrderbookUpdate)(nil),     // 4: pb.OrderbookUpdate
	(*PortfolioPLResult)(nil),   // 5: pb.PortfolioPLResult
	(*PortfolioPLPayload)(nil),  // 6: pb.PortfolioPLPayload
	(*LegsPLData)(nil),          // 7: pb.LegsPLData
	(*LegsPLPayload)(nil),       // 8: pb.LegsPLPayload
	(*BasketState)(nil),         // 9: pb.BasketState
	(*OrderInfo)(nil),           // 10: pb.OrderInfo
	(*BasketUpdatePayload)(nil), // 11: pb.BasketUpdatePayload
	(*BasketDataPayload)(nil),   // 12: pb.BasketDataPayload
	(*SendOrderCommand)(nil),    // 13: pb.SendOrderCommand
	(*SendOrderOrder)(nil),      // 14: pb.SendOrderOrder
	(*StrategyState)(nil),       // 15: pb.StrategyState
	(*StrategyConfig)(nil),      // 16: pb.StrategyConfig
	(*StrategyUpdateEvent)(nil), // 17: pb.StrategyUpdateEvent
	(*QuoteUpdateEvent)(nil),    // 18: pb.QuoteUpdateEvent
	(*PositionUpdateEvent)(nil), // 19: pb.PositionUpdateEvent
	(*RiskUpdateEvent)(nil),     // 20: pb.RiskUpdateEvent
}
var file_streams_proto_depIdxs = []int32{
	2,  // 0: pb.OrderbookUpdate.activeRange:type_name -> pb.ActiveRange
	3,  // 1: pb.OrderbookUpdate.levels:type_name -> pb.PriceLevel
	5,  // 2: pb.PortfolioPLPayload.stock:type_name -> pb.PortfolioPLResult
	5,  // 3: pb.PortfolioPLPayload.etf:type_name -> pb.PortfolioPLResult
	5,  // 4: pb.PortfolioPLPayload.future:type_name -> pb.PortfolioPLResult
	5,  // 5: pb.PortfolioPLPayload.total:type_name -> pb.PortfolioPLResult
	7,  // 6: pb.LegsPLPayload.data:type_name -> pb.LegsPLData
	9,  // 7: pb.BasketUpdatePayload.basket:type_name -> pb.BasketState
	9,  // 8: pb.BasketDataPayload.basket:type_name -> pb.BasketState
	10, // 9: pb.BasketDataPayload.orders:type_name -> pb.OrderInfo
	14, // 10: pb.SendOrderCommand.orders:type_name -> pb.SendOrderOrder
	15, // 11: pb.StrategyUpdateEvent.state:type_name -> pb.StrategyState
	16, // 12: pb.StrategyUpdateEvent.config:type_name -> pb.StrategyConfig
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_streams_proto_init() }
func file_streams_proto_init() {
	if File_streams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streams_proto_rawDesc), len(file_streams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streams_proto_goTypes,
		DependencyIndexes: file_streams_proto_depIdxs,
		MessageInfos:      file_streams_proto_msgTypes,
	}.Build()
	File_streams_proto = out.File
	file_streams_proto_goTypes = nil
	file_streams_proto_depIdxs = nil
}
