// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: exchange.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderRequest is the request body for exchange send/modify/cancel (HTTP body as protobuf).
type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	OrderGroupID  string                 `protobuf:"bytes,2,opt,name=orderGroupID,proto3" json:"orderGroupID,omitempty"`
	Ticker        string                 `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Bs            string                 `protobuf:"bytes,4,opt,name=bs,proto3" json:"bs,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *OrderRequest) GetOrderGroupID() string {
	if x != nil {
		return x.OrderGroupID
	}
	return ""
}

func (x *OrderRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *OrderRequest) GetBs() string {
	if x != nil {
		return x.Bs
	}
	return ""
}

func (x *OrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// OrderResult is the response body from exchange (HTTP body as protobuf).
type OrderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	OrderGroupID  string                 `protobuf:"bytes,2,opt,name=orderGroupID,proto3" json:"orderGroupID,omitempty"`
	Ticker        string                 `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Bs            string                 `protobuf:"bytes,4,opt,name=bs,proto3" json:"bs,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Qty           float64                `protobuf:"fixed64,6,opt,name=qty,proto3" json:"qty,omitempty"`
	PendingQty    float64                `protobuf:"fixed64,7,opt,name=pendingQty,proto3" json:"pendingQty,omitempty"`
	FilledQty     float64                `protobuf:"fixed64,8,opt,name=filledQty,proto3" json:"filledQty,omitempty"`
	AvgPrice      float64                `protobuf:"fixed64,9,opt,name=avgPrice,proto3" json:"avgPrice,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	TradeTime     string                 `protobuf:"bytes,12,opt,name=tradeTime,proto3" json:"tradeTime,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,13,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResult) Reset() {
	*x = OrderResult{}
	mi := &file_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResult) ProtoMessage() {}

func (x *OrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResult.ProtoReflect.Descriptor instead.
func (*OrderResult) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResult) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *OrderResult) GetOrderGroupID() string {
	if x != nil {
		return x.OrderGroupID
	}
	return ""
}

func (x *OrderResult) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *OrderResult) GetBs() string {
	if x != nil {
		return x.Bs
	}
	return ""
}

func (x *OrderResult) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderResult) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *OrderResult) GetPendingQty() float64 {
	if x != nil {
		return x.PendingQty
	}
	return 0
}

func (x *OrderResult) GetFilledQty() float64 {
	if x != nil {
		return x.FilledQty
	}
	return 0
}

func (x *OrderResult) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *OrderResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderResult) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderResult) GetTradeTime() string {
	if x != nil {
		return x.TradeTime
	}
	return ""
}

func (x *OrderResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_exchange_proto protoreflect.FileDescriptor

const file_exchange_proto_rawDesc = "" +
	"\n" +
	"\x0eexchange.proto\x12\x02pb\"\xbe\x01\n" +
	"\fOrderRequest\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\x12\"\n" +
	"\forderGroupID\x18\x02 \x01(\tR\forderGroupID\x12\x16\n" +
	"\x06ticker\x18\x03 \x01(\tR\x06ticker\x12\x0e\n" +
	"\x02bs\x18\x04 \x01(\tR\x02bs\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\"\xe7\x02\n" +
	"\vOrderResult\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\x12\"\n" +
	"\forderGroupID\x18\x02 \x01(\tR\forderGroupID\x12\x16\n" +
	"\x06ticker\x18\x03 \x01(\tR\x06ticker\x12\x0e\n" +
	"\x02bs\x18\x04 \x01(\tR\x02bs\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x10\n" +
	"\x03qty\x18\x06 \x01(\x01R\x03qty\x12\x1e\n" +
	"\n" +
	"pendingQty\x18\a \x01(\x01R\n" +
	"pendingQty\x12\x1c\n" +
	"\tfilledQty\x18\b \x01(\x01R\tfilledQty\x12\x1a\n" +
	"\bavgPrice\x18\t \x01(\x01R\bavgPrice\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x1c\n" +
	"\ttradeTime\x18\f \x01(\tR\ttradeTime\x12\"\n" +
	"\ferrorMessage\x18\r \x01(\tR\ferrorMessageB!Z\x1fgithub.com/trading-system/pb;pbb\x06proto3"

var (
	file_exchange_proto_rawDescOnce sync.Once
	file_exchange_proto_rawDescData []byte
)

func file_exchange_proto_rawDescGZIP() []byte {
	file_exchange_proto_rawDescOnce.Do(func() {
		file_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_proto_rawDesc), len(file_exchange_proto_rawDesc)))
	})
	return file_exchange_proto_rawDescData
}

var file_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exchange_proto_goTypes = []any{
	(*OrderRequest)(nil), // 0: pb.OrderRequest
	(*OrderResult)(nil),  // 1: pb.OrderResult
}
var file_exchange_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exchange_proto_init() }
func file_exchange_proto_init() {
	if File_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_proto_rawDesc), len(file_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exchange_proto_goTypes,
		DependencyIndexes: file_exchange_proto_depIdxs,
		MessageInfos:      file_exchange_proto_msgTypes,
	}.Build()
	File_exchange_proto = out.File
	file_exchange_proto_goTypes = nil
	file_exchange_proto_depIdxs = nil
}
